version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-235-108-68.compute-1.amazonaws.com
            database: de64iheeeab3gg
            schema: public
            user: qwvvkybqdbvwlf
            password: 80b40077e8e14dd18968ecea72fe9c185d2c2b1494b92700341741891501b183
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
