version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-231-46-238.compute-1.amazonaws.com
            database: d50pkpfki9i9fc
            schema: public
            user: fjfzzroztepbxx
            password: bec79d2d7e2bd1331bdad024d40b57a3c9487ad8b52eb65e95495a33ab3d5880
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
