version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-125-38.eu-west-1.compute.amazonaws.com
            database: dc9jodrnudmarr
            schema: public
            user: nxjkvhjwjuzgcq
            password: bbc4f6b1c880393712beee1f803f9fee7537281cef4bb2c70c1cf81c350b8c3f
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
