version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-215-41-107.compute-1.amazonaws.com
            database: d7snmvu1fqu11b
            schema: public
            user: xiuusnddofefnu
            password: c9a801066af767ca201ce452a33bdca8cf3b743415610d5bc3bd3eb804074f0e
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true